---
config:
  layout: elk
---
flowchart TB

A["Login"] -- Chauffeur --> B["Accueil"]

B -- Déclarer --> C0["Incident"]
B --> C1{"Missions en cours ?"}

C0 -- Terminer --> B

C1 -- Oui --> D0["Finir trajet"]
C1 -- Non --> D1["Commencer mission"]



D0 --> X0{"Bon Client ?"}
X0 -- Oui --> Z0
X0 -- Non --> E0
D0 -- Déclarer --> C0

Z0["Signature"] --> E0{"Suite mission ?"}
E0 -- Oui --> D0
E0 -- Non --> B

D1 --> E1{"Entretien véhicule fait ?"}
E1 -- Oui --> F1["Sélectionner mission"]
E1 -- Non --> G1["Faire entretien"]
G1 -- Terminer --> F1

F1 -- Valider --> B

