---
config:
  layout: elk
---
flowchart TB

A["Login"] -- Client --> C["Service"]
C -- Sélectionner --> C
C -- Consulter --> C0["Historique"]
C -- Acheter --> C1["Panier"]

C0 -- Voir --> C0
C0 -- Vérification --> D0{"Commande validé par admin ?"}
D0 -- Oui --> C0 
D0 -- Non --> E0["Commandes"]
E0 -- Modifier --> E0
E0 -- Valider --> C0

C1 -- Commander --> D1{"Commande en cours ?"}
D1 -- Oui --> E1{"Bloqué par admin ?"}
D1 -- Non --> F1["Nouvelle Commande"]

E1 -- Oui --> F1
E1 -- Non --> G1["Ancienne Commande"]

F1 & G1 -- Ajouter --> H1{"Ajouter Produits ?"}
H1 -- Oui --> H1
H1 -- Non --> I1["Valider commande"]
I1 -- Envoyer --> J1["Requête de validation à l'admin"]
I1 -- Redirigier --> C