---
config:
  layout: elk
---
flowchart TB

A["Login"] -- Gestionnaire --> B["Accueil"]

B -- Accéder --> C0["Commandes"]
B -- Gérer --> C1["Stock"]

C0 -- Historique --> C0
C0 -- Vérifier --> D0{"Nouvelles commandes validées par l'admin ?"}

D0 -- Non --> C0
D0 -- Oui --> E0["Préparation commandes"]

E0 -- Ajouter --> F0["Produits"]

F0 -- Mettre à jour --> C1
F0 --> G0{"Quantité suffisante ?"}

G0 -- Oui --> H0["Commande prête à être livré"]
G0 -- Non --> I0["Envoie message client"]

I0 -- Valider --> H0

H0 -- Retour automatique --> C0



