services:
 nginx-commandes:
  image: nginx:latest
  container_name: nginx-commandes
  restart: always
  ports:
    - "4400:80"
  volumes:
    - .:/var/www/html
    - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  depends_on:
    - php-fpm-commandes
  networks:
    - app-network-commandes

 php-fpm-commandes:
   build: ./app
   container_name: php-fpm-commandes
   restart: always
   volumes:
    - .:/var/www/html
   working_dir: /var/www/html
   command: bash -c "chown -R www-data:www-data /var/www/html/writable && php-fpm"
   depends_on:
     - mariadb-commandes
   networks:
     - app-network-commandes

 mariadb-commandes:
  image: mariadb:11.3
  container_name: mariadb-commandes
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: appdb
    MYSQL_USER: user
    MYSQL_PASSWORD: admin
  volumes:
    - db_data:/var/lib/mysql
    - ./sql:/docker-entrypoint-initdb.d
    - ./mariadb/my.cnf:/etc/mysql/conf.d/my.cnf
  networks:
    - app-network-commandes

 phpmyadmin-commandes:
  image: phpmyadmin:latest
  container_name: phpmyadmin-commandes
  restart: always
  depends_on:
    - mariadb-commandes
  ports:
    - "4481:80"
  environment:
    PMA_HOST: mariadb-commandes
    PMA_PMADB: phpmyadmin-commandes
    PMA_USER: user
    PMA_PASSWORD: admin
    PMA_CONTROLUSER: pma
    PMA_CONTROLPASS: pmapass
    UPLOAD_LIMIT: 50M
  networks:
    - app-network-commandes

networks:
  app-network-commandes:
    external: true

volumes:
   db_data:
